### ISSUE TITLE
Failure to Write rst7 files

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/biosimspace#17] opened 2023-03-10 14:58 UTC
Hi,

This is likely more of a sire issue, but I'm getting some strange behaviour when trying to save rst files. When I run the following script:

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["BSS_VERBOSE_ERRORS"] = "1"
import BioSimSpace as BSS

system = BSS.IO.readMolecules(["free_preequil.prm7", "free_preequil.rst7"])

protocol = BSS.Protocol.Production( runtime=100*BSS.Units.Time.picosecond)

#process = BSS.Process.Gromacs(system, protocol, work_dir="output")
# The SOMD process below runs extremely slowly due to very low n_moves
process = BSS.Process.Somd(system, protocol, platform="CUDA",  work_dir="output", extra_options={"n_moves": 50000, "n_cycles":1})
process.start()
process.wait()
# If block==True, then saving to the rst7 (but not prm7) file will fail
final_system = process.getSystem(block=False)

if process.isError():
    print(process.stdout())
    print(process.stderr())
    raise BSS._Exceptions.ThirdPartyError("The process failed.")
if system is None:
    print(process.stdout())
    print(process.stderr())
    raise BSS._Exceptions.ThirdPartyError("The process failed.")

print(system)
BSS.IO.saveMolecules(f"output_sys", final_system, fileformat=["rst7", "prm7"])
```

I consistently get the following error:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/finlayclark/software/devel/BioSimSpace_own/python/BioSimSpace/IO/_io.py:723 in             │
│ saveMolecules                                                                                    │
│                                                                                                  │
│    720 │   │   │   if format == "PRM7" or format == "RST7":                                      │
│    721 │   │   │   │   system_copy = system.copy()                                               │
│    722 │   │   │   │   system_copy._set_water_topology("AMBER", _property_map)                   │
│ ❱  723 │   │   │   │   file = _SireIO.MoleculeParser.save(                                       │
│    724 │   │   │   │   │   system_copy._sire_object, filebase, _property_map                     │
│    725 │   │   │   │   )                                                                         │
│    726 │   │   │   elif format == "GroTop":                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: SireError::io_error: Cannot write the (perhaps some of the ) files as the following errors occurred:
Failed to write the file '/home/finlayclark/Documents/research/adaptive_sampling/full_run_test/test_getSystem/output_sys.rst7' using the parser for 
fileformat 'RST7'. Errors reported by the parser are:
Errors converting the system to a Amber Rst7 format...
Could not write the float at index 12149, value '-1072.48' into the specified format AmberFormat( 6 x float[width = 12, precision = 7] ). (call 
sire.error.get_last_error_details() for more info)

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/finlayclark/Documents/research/adaptive_sampling/full_run_test/test_getSystem/test_getSyst │
│ em.py:28 in <module>                                                                             │
│                                                                                                  │
│   25 │   raise BSS._Exceptions.ThirdPartyError("The process failed.")                            │
│   26                                                                                             │
│   27 print(system)                                                                               │
│ ❱ 28 BSS.IO.saveMolecules(f"output_sys", final_system, fileformat=["rst7", "prm7"])              │
│   29                                                                                             │
│                                                                                                  │
│ /home/finlayclark/software/devel/BioSimSpace_own/python/BioSimSpace/IO/_io.py:759 in             │
│ saveMolecules                                                                                    │
│                                                                                                  │
│    756 │   │   except Exception as e:                                                            │
│    757 │   │   │   msg = "Failed to save system to format: '%s'" % format                        │
│    758 │   │   │   if _isVerbose():                                                              │
│ ❱  759 │   │   │   │   raise IOError(msg) from e                                                 │
│    760 │   │   │   else:                                                                         │
│    761 │   │   │   │   raise IOError(msg) from None                                              │
│    762                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: Failed to save system to format: 'RST7'
```

However, if I set `final_system = process.getSystem(block=False)`, then this works without issue consistently. Please see the script and input [here](https://github.com/OpenBioSim/biosimspace/files/10943109/issue.tar.gz).

I attempted to test this with SOMD too (to check if the issue was just gromacs -> amber conversion), but the default simfile options meant that SOMD ran too slowly to complete even a short test (I'll raise a separate issue about this). 

The reason that I have been setting `block=True` in `getSystem` is that this was often returning None instead of a system, despite running `process.wait()` beforehand, e.g. [here](https://github.com/fjclark/EnsEquil/blob/3d2b70166a800438364f611ee5e9bf0184e29681/EnsEquil/leg.py#L530). However, I have so far been unable to reproduce this in a short script so far.

 - OS: Ubuntu 22
 - Version of Python: 3.9.15
 - Version of BioSimSpace: latest `dev` release, installed this morning

Thanks.

**Comment by fjclark** [comment] 2023-03-10 15:11
If I overwrite the default SOMD `ncycles` and `nmoves` to allow it to run in reasonable time:

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["BSS_VERBOSE_ERRORS"] = "1"
import BioSimSpace as BSS

system = BSS.IO.readMolecules(["free_preequil.prm7", "free_preequil.rst7"])

protocol = BSS.Protocol.Production( runtime=100*BSS.Units.Time.picosecond)

#process = BSS.Process.Gromacs(system, protocol, work_dir="output")
# The SOMD process below runs extremely slowly due to very low n_moves
process = BSS.Process.Somd(system, protocol, platform="CUDA",  work_dir="output", extra_options={"nmoves": 50000, "ncycles":1})
process.start()
process.wait()
# If block==True, then saving to the rst7 (but not prm7) file will fail
final_system = process.getSystem(block=True)

if process.isError():
    print(process.stdout())
    print(process.stderr())
    raise BSS._Exceptions.ThirdPartyError("The process failed.")
if final_system is None:
    print(process.stdout())
    print(process.stderr())
    raise BSS._Exceptions.ThirdPartyError("The process failed.")

print(system)
BSS.IO.saveMolecules(f"output_sys", final_system, fileformat=["rst7", "prm7"])
```

Then `getSystem()` returns `None`, regardless of whether `block=True` (previously setting `block=True` seemed to fix this).

```
###===========================================================###

###=======================somd run============================###
Starting somd run...
50000 moves 1 cycles, 100 ps simulation time

Cycle =  1
Simulation took 8 s
Saving restart
Starting /home/finlayclark/anaconda3/envs/mamba/envs/ensequil/bin/somd: number of threads equals 20
None
All output has been redirected to the stdout stream!
None
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/finlayclark/Documents/research/adaptive_sampling/full_run_test/test_getSystem/test_getSyst │
│ em.py:25 in <module>                                                                             │
│                                                                                                  │
│   22 if final_system is None:                                                                    │
│   23 │   print(process.stdout())                                                                 │
│   24 │   print(process.stderr())                                                                 │
│ ❱ 25 │   raise BSS._Exceptions.ThirdPartyError("The process failed.")                            │
│   26                                                                                             │
│   27 print(system)                                                                               │
│   28 BSS.IO.saveMolecules(f"output_sys", final_system, fileformat=["rst7", "prm7"])              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ThirdPartyError: The process failed.
```

**Comment by fjclark** [comment] 2023-03-10 15:42
If I add
```
BSS.IO.saveMolecules(f"output_sys", final_system, fileformat=["rst7", "prm7"], property_map={"velocity" : "foo"})
```
this prevents the error. 

For the SOMD issue, I supply `extra_options={"nmoves": 50000, "ncycles":1}`, but don't change anything else. This results in the above failure a trajectory with 1 frame. I also tried using  `extra_options={"nmoves": 5000, "ncycles":10}` and confirmed that this results in a trajectory with 10 frames, and gives the same error due to `system == None`.

**Comment by lohedges** [comment] 2023-03-10 15:45
Thanks. I forgot SOMD now uses `extra_options`, so as you've found it will self-consistently adapt other options that depend on the ones you overload. I'll run the example myself to see why no system is returned.

**Comment by lohedges** [comment] 2023-03-10 16:24
If I raise the exception within `getSystem` I see that it's failing when trying to updated the coordinates and velocities in the original system:

```python
UserWarning: SireError::incompatible_error: Couldn't update coordinates for molecule index '0' 
```

I'll load the files manually to try to work out why this is.

**Comment by chryswoods** [comment] 2023-03-10 16:36
Is the value the coordinates? The value '-1072.48' overflows the 12.7 float specification so can't be written (you number has 6 characters before the decimal point, which is more than the 5 available for a 12.7 float). 

This can sometimes happen in MD with coordinates if you don't have a periodic box and the molecule flies off into the ether. Or if you have a periodic box and don't wrap coordinates back into the box and the molecule has translated a long way out of the central box.

**Comment by chryswoods** [comment] 2023-03-10 16:38
The best solution is to use the binary Amber format (rst) as this isn't limited by the character width format.

**Comment by lohedges** [comment] 2023-03-10 16:45
Okay, it seems that something is going wrong with working out the mapping between molecules in the original system (the one passed to the process) and the one written by SOMD. The issue is that SOMD _completely_ reorders the molecules in the system on startup, making it a complete pain to update coordinates and velocities. (We want to return a system to the user that is compatible with the one that they passed in, i.e. with the molecules in the same order.)

There is logic in some C++ wrapped code to do this, which has worked well to date, but seems to be failing here. I'll try to figure out why, but I really can't wait for SOMD2 and not needing these (brittle) workarounds.

**Comment by chryswoods** [comment] 2023-03-10 16:47
The protocol looks like a gas phase MD simulation in gromacs? Has a Center of Mass / Rotation constraint been added to the protocol for gromacs so that any global translation and rotation of the molecule has been removed? If not, then I can believe that the molecule has just flown away from the origin and fails when it has translated so one of its atoms has a coordinate of -1000

**Comment by lohedges** [comment] 2023-03-10 16:56
Looking at the `latest.pdb` file it's clear that the atoms don't have unique numbers, which is essentially for the molecule re-mapping to work correctly. I'm not sure what's changed to cause this, since they should come from the numbers for the system passed in, which are made unique behind the scenes.

**Comment by fjclark** [comment] 2023-03-10 17:36
>The best solution is to use the binary Amber format (rst) as this isn't limited by the character width format.

Thanks!

> The protocol looks like a gas phase MD simulation in gromacs? Has a Center of Mass / Rotation constraint been added to the protocol for gromacs so that any global translation and rotation of the molecule has been removed? If not, then I can believe that the molecule has just flown away from the origin and fails when it has translated so one of its atoms has a coordinate of -1000

This is a simulation of a ligand in a 40 A^3 periodic box of water. This seems to be a velocity given that removing the velocities by adding property_map={"velocity" : "foo"}) consistently solves the issue.

**Comment by lohedges** [comment] 2023-03-10 21:01
Okay, something has gone wrong with the change to Sire 2023. As mentioned previously, the issue with SOMD is that it re-orders the molecules on startup, so that you need to re-map coordinates and velocities to the molecules in the original system passed into the process. (SOMD does this because it does stuff using containers of molecules based on data structures that don't preserver order.) This is a _pain_ to handle, since there will be _lots_ of molecules that look the same, e.g. waters, so you there isn't an easy way to map, especially given that the ordering is random.

My approach is to store a renumbered version of the SIre system within the SOMD process. In this system all of the atoms and residues are renumbered in ascending order by molecule index. Although SOMD reorders the molecules on startup, the atom/residue numbering was preserved so I could use this to re-map, i.e. I just found matched molecules where the first atom had the same atom number.

With the 2023 code I get a `latest.pdb` that looks like this:

```
ATOM      1  O   WAT    71     -11.544  17.460  52.128  1.00  0.00           O
ATOM      2  H1  WAT    71     -10.979  17.520  51.357  1.00  0.00           H
ATOM      3  H2  WAT    71     -11.954  16.598  52.058  1.00  0.00           H
TER
ATOM      1  O   WAT    72      -3.023 -80.972  46.751  1.00  0.00           O
ATOM      2  H1  WAT    72      -2.284 -81.003  46.143  1.00  0.00           H
ATOM      3  H2  WAT    72      -3.059 -81.850  47.129  1.00  0.00           H
TER
ATOM      1  O   WAT    73      -7.680  42.687 -49.750  1.00  0.00           O
ATOM      2  H1  WAT    73      -7.670  43.250 -50.524  1.00  0.00           H
ATOM      3  H2  WAT    73      -8.589  42.397 -49.677  1.00  0.00           H
TER
ATOM      1  O   WAT    74      34.667  63.460 -89.591  1.00  0.00           O
ATOM      2  H1  WAT    74      34.069  64.161 -89.850  1.00  0.00           H
ATOM      3  H2  WAT    74      34.348  63.178 -88.733  1.00  0.00           H
TER
...
```

(Here I'm just showing the first few molecules.)

With pre-2023, installed using:

```
mamba create -n test -c conda-forge -c michellab biosimspace=2022.2.1  
```

I get the following:

```
ATOM    209  O   WAT    60      52.073 -20.496 -27.032  1.00  0.00           O
ATOM    210  H1  WAT    60      52.049 -20.111 -27.908  1.00  0.00           H
ATOM    211  H2  WAT    60      51.200 -20.868 -26.910  1.00  0.00           H
TER
ATOM    206  O   WAT    59     126.737 105.696  10.556  1.00  0.00           O
ATOM    207  H1  WAT    59     126.627 105.466   9.633  1.00  0.00           H
ATOM    208  H2  WAT    59     126.335 104.970  11.033  1.00  0.00           H
TER
ATOM    203  O   WAT    58      50.825 -37.753 -64.522  1.00  0.00           O
ATOM    204  H1  WAT    58      50.622 -38.678 -64.656  1.00  0.00           H
ATOM    205  H2  WAT    58      51.771 -37.733 -64.378  1.00  0.00           H
TER
ATOM    200  O   WAT    57      50.003   9.463  24.952  1.00  0.00           O
ATOM    201  H1  WAT    57      50.820   9.643  25.416  1.00  0.00           H
ATOM    202  H2  WAT    57      50.098   8.562  24.640  1.00  0.00           H
TER
...
```

(Note that the atom numbering is different from run-to-run, but the important thing is that the atom numbers are unique.)

As of yet I have no idea as to what internal change may have caused this. My code to renumber the atoms and residues is still working, as is the remapping code when the `latest.pdb` file contains unique atoms. I'll first look at the edits to SOMD to make it work with the new API.

@chryswoods: Can you think of any changes under the hood that might have changed this behaviour. I'm kind of surprised that each molecule has the same numbering in the 2023 code. Normally the indices are the same, but the numbering is unique to the molecule. (If they were loaded from file, they keep the numbering in the file.)

**Comment by lohedges** [comment] 2023-03-10 21:05
@fjclark: For the situations that worked, you might have got lucky that the protein and ligand mapped correctly. Given the above, I wouldn't trust anything thought since it's unlikely every molecule re-mapped perfectly, i.e. all of the waters / ions, etc.

**Comment by lohedges** [comment] 2023-03-10 21:18
It looks like the `sire.legacy.IO.PDB2` parser that is broken. Will try to figure out what change has caused this.

**Comment by lohedges** [comment] 2023-03-10 23:13
This is now fixed in Sire and will likely be available early next week. Thanks for reporting!

**Closed** 2023-03-11 14:39 UTC
Labels: bug

**Comment by fjclark** [comment] 2023-03-13 09:10
Brilliant, thanks very much!
