### ISSUE TITLE
[BUG] Unable to save to RST7 file

### ISSUE THREAD

**Issue by xiki-tempula** [OpenBioSim/biosimspace#130] opened 2023-07-07 13:32 UTC
**Describe the bug**
I have a Gromacs topology and coordinate file and I tried to save it as RST7 file

**To Reproduce**
```
In [1]: import BioSimSpace.Sandpit.Exscientia as BSS

In [7]: mol = BSS.IO.readMolecules(['test.top', 'test.gro'])

In [8]: BSS.IO.saveMolecules('test', mol, 'rst7')
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /exs/shared/collaboration/teams/mdteam/envs/asfe/lib/python3.8/site-packages/BioSimSpace/Sandpit │
│ /Exscientia/IO/_io.py:757 in saveMolecules                                                       │
│                                                                                                  │
│    754 │   │   │   if _isVerbose():                                                              │
│    755 │   │   │   │   raise IOError(msg) from e                                                 │
│    756 │   │   │   else:                                                                         │
│ ❱  757 │   │   │   │   raise IOError(msg) from None                                              │
│    758 │                                                                                         │
│    759 │   # Return the list of files.                                                           │
│    760 │   return files                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: Failed to save system to format: 'rst7'
```

**Expected behavior**
It writes

**Input files**
[Archive.zip](https://github.com/OpenBioSim/biosimspace/files/11982466/Archive.zip)

**(please complete the following information):**
 - OS: Linux
 - Version of Python: 3.8
 - Version of BioSimSpace: [e.g. 2023.1, or latest `dev` release]
 - sire                      2023.3.0         py38h3fd9d12_0    openbiosim/label/main
 - biosimspace               2023.3.0                 py38_0    openbiosim/label/main
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

**Comment by lohedges** [comment] 2023-07-07 14:00
In this case, it's the velocities, so the file can be written using:

```python
In [5]: BSS.IO.saveMolecules("test", s, "rst7", property_map={"velocity":"null"})
Out[5]: ['/home/lester/Downloads/Archive/test.rst7']
```

**Comment by lohedges** [comment] 2023-07-07 14:05
Duplicate of michellab/BioSimSpace#404.

**Comment by xiki-tempula** [comment] 2023-07-07 14:57
Why would the velocity be a problem in this case? It seems to me that the velocity is fine?

**Comment by chryswoods** [comment] 2023-07-07 15:01
The challenge is that rst7 is a fixed format file. Numbers are written using a 12.7 specifier, meaning there is only space for 4 columns before the decimal point, then a decimal point, then 7 columns after the decimal point.

The velocity "-1203.8" needs 5 columns before the decimal point, so it can't be written using the 12.7 format specifier used by rst7.

It would be better to use the binary Amber rst format if you want velocities. It is too easy for velocities to become larger than can be fitted into a rst7 file.

**Comment by chryswoods** [comment] 2023-07-07 15:01
The challenge is that rst7 is a fixed format file. Numbers are written using a 12.7 specifier, meaning there is only space for 4 columns before the decimal point, then a decimal point, then 7 columns after the decimal point.

The velocity "-1203.8" needs 5 columns before the decimal point, so it can't be written using the 12.7 format specifier used by rst7.

It would be better to use the binary Amber rst format if you want velocities. It is too easy for velocities to become larger than can be fitted into a rst7 file.

**Comment by xiki-tempula** [comment] 2023-07-07 15:03
@chryswoods Thanks. Do you know which atom is giving this velocity? I don't think any atom should have a velocity this high

**Comment by xiki-tempula** [comment] 2023-07-07 15:13
Ok, you are right.
Gromacs has a velocity of nm/ps
Amber has a velocity unit of Angstroms/20.455 ps
-5.88 nm/ps is -1203.8 Angstroms/20.455 ps

**Comment by chryswoods** [comment] 2023-07-07 16:42
Yes - it is a challenge with rst7 formats. It is best treated as a "legacy" file format, and alternatives that store coordinate as binary data should be preferred (e.g. rst or xdr)

**Closed** 2023-08-11 19:02 UTC
Labels: exscientia
