### ISSUE TITLE
[BUG] BSS.FreeEnergy.Relative() automatically sets GPU index in somd.cfg

### ISSUE THREAD

**Issue by jasmin-guven** [OpenBioSim/biosimspace#180] opened 2023-10-06 13:03 UTC
**Describe the bug**
When setting up a free energy calculation for SOMD, BSS sets the gpu index in the configuration file automatically. This causes problems when used with e.g. SLURM

**To Reproduce**
```
config_options = {"ncycles": n_cycles, 
                  "nmoves": n_moves, 
                  "buffered coordinates frequency": frames, 
                  "cutoff distance": "8 angstrom", 
                  "minimise": False}
bss.FreeEnergy.Relative(system=unbound, protocol=free_energy_protocol, engine="SOMD", work_dir=unbound_directory, extra_options=config_options, setup_only=True)
```

If the above is run without SLURM, e.g. in VSCode debugger, the gpu index is not set as I don't think I have `CUDA_VISIBLE_DEVICES` set in my environment. As soon as I submit my SLURM workflow, SOMD sets the gpu index from SLURM in an unknown way (to me). 

**Expected behavior**
Gpu index should be set externally in the first place in a bash or SLURM script.

**(please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Version of Python: 3.9.17
 - Version of BioSimSpace: 2023.3.0
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: [no]

**Comment by lohedges** [comment] 2023-10-06 13:34
Sorry, I'm confused as to what the problem is here? Are you getting an invalid device index? The CUDA support in SOMD (via OpenMM) is _entirely_ dependent on the `CUDA_VISIBLE_DEVICES` environment variable being set correctly, OpenMM won't work without this being the case. The `gpu` option in the SOMD config _shoud_ be the index into the `CUDA_VISIBLE_DEVICES` list, not the actual index of the device. However, looking at the code it does seem to be choosing the first entry from the list. (I'll debug this.) The SOMD help documentation was actually wrong about what the `gpu` option means, as you can see [here](https://github.com/openmm/openmm/issues/2190).

On a cluster, `CUDA_VISIBLE_DEVICES` will typically be set for you by the scheduler, i.e. it will only make visible to you the devices that are part of your allocation. Assuming that you only want to run on a single GPU, then the `gpu` option should just be zero, which is the default option in SOMD.

If you are trying to run the above in an environment where `CUDA_VISIBLE_DEVICES` isn't set, then the code will fallback to using the CPU, which probably isn't what you want. You can always manually specify a GPU index by passing `extra_options` to th e `FreeEnergy.Relative` constructor, i.e. `extra_options={"gpu": 0}`. This will override any options that are automatically set.

**Comment by lohedges** [comment] 2023-10-06 13:43
I've checked the SOMD setup code in BioSimSpace and there looks like a regression. I'm not sure if this is related to your issue, but I'll fix this anyway.

**Comment by annamherz** [comment] 2023-10-06 13:59
hello! I think I've had a similar issue before. The problem for me arises I think from when the input files are generated vs when the production run using them takes place. If the files are run outside of BSS in a parallel fashion using a slurm job scheduler, with each lambda window on a different GPU, this doesn't then match the GPU that was written during the file generation (if this was a previous slurm job assigned to a different GPU) and leads to the run terminating.

**Comment by jasmin-guven** [comment] 2023-10-06 14:03
> Are you getting an invalid device index?

Hi Lester, 

Sorry yes I get an invalid device index. 

I think Anna explains the issue much better! I also run my whole workflow as a SLURM submission script as: 

```
N_LIGANDS=NUMBER_OF_LIGANDS
ENGINE=ENGINE
AFE_INPUT_DIR=AFE_PATH

export ligands_dat_file=LIGANDS_DATA_FILE
export transformations_file=TRANSFORMATIONS_DATA_FILE

source $MEZEHOME/parse.sh 

solvation_job_id=$(sbatch --parsable --array=1-$N_LIGANDS $AFE_INPUT_DIR/02_add_water.sh)
echo "Adding water with slurm job $solvation_job_id"

heating_job_id=$(sbatch --dependency=afterok:${solvation_job_id} --parsable --array=1-$N_LIGANDS $AFE_INPUT_DIR/03_heat_meze.sh)
echo "Heating meze with slurm job $heating_job_id"

meze_job_id=$(sbatch --dependency=afterok:${heating_job_id} --parsable --array=0-$((${#transformations_array[@]}-1)) $AFE_INPUT_DIR/04_meze.sh)
echo "Preparing AFE with slurm job $prepafe_job_id"

for i in "${!transformations_array[@]}"
do
    afe_job_id=$(sbatch --dependency=afterok:${meze_job_id} --parsable --job-name=${transformations_array[i]} --array=0-$((${n_windows_array[i]}-1)) $AFE_INPUT_DIR/run_$ENGINE.sh ${transformations_array[i]} "${lambdas_array[i]}")
    echo "Submitted AFE slurm job $afe_job_id"
done
```

I.e. I'm preparing, minimising and equilibrating & running different lambdas on different gpus.

Hope this explains it further!

**Comment by lohedges** [comment] 2023-10-06 14:16
Okay, this makes sense. I was thinking that it was something about setup being in a different place to where the runs were being done.

I've checked the SOMD code and what I said above is wrong, i.e. it does set the device index explicitly (rather than indexing `CUDA_VISIBLE_DEVICES`) so the change in BioSimSpace was correct. What I originally suggested would work in your case, since `gpu` would be used as an index into `CUDA_VISIBLE_DEVICES`, which would be set by the scheduler at the time of running, i.e. what you want. Since the device index is being set directly, it doesn't make to specify one before running since we don't know what it will be.

I'll have a think about what to do. It might be a case of needing to patch the config file when the job runs, i.e. querying `CUDA_VISIBLE_DEVICES`, then overwriting the value of `gpu` in the config. There isn't really a way to do this in BioSimSpace, so would need to be done in your submission script, e.g. something like:

```sh
# Get the first available GPU index.
gpu=$(echo $CUDA_VISIBLE_DEVICES | awk -F ',' '{print $1}')

# Replace the gpu option in the config.
sed -i "/gpu/c\gpu = $gpu" somd.cfg
```

**Comment by jasmin-guven** [comment] 2023-10-06 14:24
Thanks for explaining! I think your suggestion makes sense. 

What I've done in the meantime is to write this function to just remove the gpu line from the config entirely and this seems to be working:

```
  for i in range(len(files)):
      with open(files[i], "r") as f:
          old_config = f.readlines()
      for line in old_config:
          if "gpu" in line:
              idx = old_config.index(line)
              del old_config[idx]
      replaced_config = old_config
      with open(files[i], "w") as f:
          f.writelines(replaced_config)
```

I think Anna said she commented out the line in  `_generate_config()` which writes the gpu id in the config, so the line doesn't get written at all.

**Comment by lohedges** [comment] 2023-10-06 14:51
I guess so. I just would have thought that if you request a single GPU on a multi-gpu machine then it would mask out the device index for you, e.g. you could get `CUDA_VISIBLE_DEVICES=1` or something. Maybe it's doing some magic behind the scenes to actually remap this to the correct index.

What I'm confused about is why you are getting a non-zero value in the configuration file on setup? By default it will choose the `CUDA` platform if `CUDA_VISIBLE_DEVICES` is set, then the value of `gpu` will be set to the _first_ free device. You should only end up with a non-zero value if the first visible device index is non-zero. (Perhaps this is the case on your setup machine?)

**Comment by lohedges** [comment] 2023-10-06 15:03
I've now played around locally and it seems that the original behaviour that I suggested is correct, i.e. `gpu` should be an index into the `CUDA_VISIBLE_DEVICES` array, so always setting to zero for single GPU jobs is the correct behaviour. I'll fix this now. Apologies for the confusion.

**Comment by annamherz** [comment] 2023-10-06 16:32
> I guess so. I just would have thought that if you request a single GPU on a multi-gpu machine then it would mask out the device index for you, e.g. you could get `CUDA_VISIBLE_DEVICES=1` or something. Maybe it's doing some magic behind the scenes to actually remap this to the correct index.

I've uncommented the line and run it through my scripts, and with that it will eg set `gpu = 3` , so I guess it was taking the gpu the script generation was running on. Not sure if this is related to how slurm assigns visible devices when allocating jobs.

> I've now played around locally and it seems that the original behaviour that I suggested is correct, i.e. `gpu` should be an index into the `CUDA_VISIBLE_DEVICES` array, so always setting to zero for single GPU jobs is the correct behaviour. I'll fix this now. Apologies for the confusion.

Great thank you!

**Closed** 2023-10-11 09:05 UTC
Labels: bug
